version: '3.1'

services:
  organiza_ai_db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=root
      - POSTGRES_DB=organiza_ai

  organiza_ai:
    image: grpc-organiza_ai
    ports:
      - 50052:50052 # mobile and desktop gRPC port
      - 50051:50051 # web gRPC port
      - 80:80 # Web App access port via nginx (http)
      - 443:443 # Web App access port via nginx (https)
    restart: always
    environment:
      - DATABASE_PWD=example # Same as the POSTGRES_PASSWORD
      - DATABASE_USER=root # Same as the POSTGRES_USER
      - DATABASE_HOST=192.168.0.52 # Must be ip or hostname, as localhost reefer to the container itself
    depends_on:
      - organiza_ai_db
    extra_hosts:
      - "organiza_ai.com:172.0.0.1" # Put the server IP
