version: '3.1'

services:

  grpc:
    image: grpc-organiza_ai
    ports:
      - 50051:50051
      - 80:80
      - 443:443
      - 50052:50052
      - 9901:9901
    restart: always
    environment:
      - DATABASE_PWD=example
      - DATABASE_USER=root
      - DATABASE_HOST=192.168.0.51
